version: '3.8'

services:
  pac-portal:
    build: .
    container_name: pac_bandeirantes_portal
    ports:
      - "10001:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - PORT=3000
    restart: always
