version: '3.8'

services:
  pac-portal:
    image: nginx:alpine
    container_name: pac_bandeirantes_portal
    ports:
      - "10001:80"
    volumes:
      - .:/usr/share/nginx/html/pac2026
    restart: always
